### ISSUE TITLE
Ability to exclude a pattern

### ISSUE THREAD

**Issue by bric3** [notken12/licensesnip#3]
I have in my project a set of files I would like to avoid touching, because they have another license.

E.g. excluding a pattern like `**/internal/shadowed/**`

This would be practical.

**Comment by notken12** [comment]
Great idea, I added it in version 1.5.0. Just add a file called .licensesnipignore and use it in the same way as .gitignore 👍

**Comment by bric3** [comment]
Cool thank you !
